[package]
name = "aes_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.7.0"
block-modes = "0.8.1"
hex-literal = "0.3.1"

# package added for debugging
hex = "0.4.3"
openssl = "0.10.72"
